### ISSUE TITLE
IP address checking must follow the netmask

### ISSUE THREAD

**Issue by ejpcmac** [nerves-project/dhcp_server#5]
Currently, `validate_ip/2` considers all IPs are class C (netmask `255.255.255.0`), no matter the provided netmask. This can cause the DHCP server to fail if we want to use another netmask.

To check if two IPs are in the same network, we should:

```elixir
use Bitwise

# 1. Get their respective network
{a, b, c, d} = netmask

{a1, b1, c1, d1} = ip1
net1 = {a1 &&& a, b1 &&& b, c1 &&& c, d1 &&& d}

{a2, b2, c2, d2}  = ip2
net2 = {a2 &&& a, b2 &&& b, c2 &&& c, d2 &&& d}

# 2. Compare the networks
net1 === net2
```

Or, like in the Erlang implementation, convert the IP to an integer and do the `&&&` directly on integers.

I may push a pull request tomorrow to do this and #4. Don’t hesitate to ask me if you finally have no news.

**Comment by ConnorRigby** [comment]
So sorry about the wait here. I was away when this came in and then forgot about it when i got back. If you have a PR feel free to submit it, if not i will be sure to tackle this soon.

**Comment by ejpcmac** [comment]
@ConnorRigby No problem :-) It is on my pipeline, but I’ve done so many other things since I originally scheduled it and I’m not likely to work on it before a few weeks given my current pipeline state. If you’re ready to do something before me, you can do.

**Comment by ejpcmac** [comment]
@ConnorRigby It reached the top of my TODO pipeline. Are you on it or should I do something?

**Comment by ConnorRigby** [comment]
I've not had time to get to this. Feel free to PR anything in.
